apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-gen-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-gen-app
  template:
    metadata:
      labels:
        app: log-gen-app
    spec:
      containers:
      - name: log-gen-app
        image: log_gen_app_1:latest
        imagePullPolicy: Never
